Implement faster algorithm
paul-schreiber/secret-santa pull request #1
Opened 2023-10-24 13:20 UTC by mangerlahn

Okay, ich hab mich mal an dem Algorithmus versucht, ist basically ein rewrite geworden. Ich hab den erst in Swift gebaut und dann in TS überführt. Der Code ist vermutlich nicht geil. Ich hoffe das ist richtig so 😂

2023-10-24 13:33 UTC, mangerlahn commented
Das Ding sucht jetzt natürlich nicht nach einem Kreis, in dem alle sind. Könnte man sicher auch bauen, ist dann nur komplexer.

2023-10-27 17:13 UTC, paul-schreiber commented
> Das Ding sucht jetzt natürlich nicht nach einem Kreis, in dem alle sind. Könnte man sicher auch bauen, ist dann nur komplexer.

Das war ja eine der Anforderungen 😂 
Aber ist auf jeden Fall ne solide Alternative, weil sie ja nur eine Möglichkeit sucht.

2023-10-28 08:02 UTC, paul-schreiber requested changes
Danke fürs umsetzen! :)
Auf jeden Fall die bessere Lösung für große Gruppen.

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +        this.availableSantas = players.map((player) => { return player.id })
```suggestion
        this.availableSantas = players.map((player) => player.id)
```

Wenn du nur einen Wert returnst kannst du hier die Short-Form nutzen :)

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +        this.availableSantas = players.map((player) => { return player.id })
availableSantaIds wäre noch passender oder?

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +			this.availableSantas = this.availableSantas.filter((santa) => { return santa != currentSanta.santa })
```suggestion
			this.availableSantas = this.availableSantas.filter((santa) => santa != currentSanta.santa)
```
shortForm :)

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +			this.availablePresentees = this.availablePresentees.filter((santa) => { return santa != currentSanta.presentee })
```suggestion
			this.availablePresentees = this.availablePresentees.filter((santa) => santa != currentSanta.presentee)
```

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +        let availableNodes = this.santas
availableSantaNodes fände ich hier noch aussagekräftiger 😊

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +
```suggestion
           .sort((p1, p2) => p1[1] - p2[1])
           .map(([presentee]) => presentee)
```
Hier würde ich gleich mappen, weil du ja die Länge nach dem Sortieren nicht mehr brauchst :)

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +            return node.possiblePresentees.length === count
```suggestion
         const minPresenteeCount = Math.min(...availableSantaNodes.map((node) => node.possiblePresentees.length))
        availableSantaNodes = availableSantaNodes.filter((node) => node.possiblePresentees.length === minPresenteeCount)
```

Hier kannst du auch min() nutzen und hast bisschen weniger Schreibaufwand :)

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +        const presentee = presentees.filter((presentee) => { return node.possiblePresentees.includes(presentee[0]) })[0]
```suggestion
        const presentee = presentees.find((presentee) => node.possiblePresentees.includes(presentee))
```
Statt filter()[0] kannst du auch .find() nutzen

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +
```suggestion
        if (!presentee) throw 'UNDEFINED-CIRCLE'
```

Hier vielleicht noch ein Fallback falls was crashen sollte und find() nichts liefert

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +        return this.santas.filter((santa) => { return santa.id === id })[0]
```suggestion
        return this.santas.find((santa) => santa.id === id )
```

find() statt filter()[0] und shortForm :)

2023-10-28 08:02 UTC, paul-schreiber commented on SantaFinder.ts
> +import { Santa, SantaNode } from "./types"
Den neuen Type brauchst du mit den Anpassungen nicht mehr :)

2023-10-28 08:02 UTC, paul-schreiber commented on types.ts
> +type SantaNode = {
Brauchst du dann nicht mehr :)

2023-10-28 08:17 UTC, mangerlahn commented
Danke für das Review! Einiges gelernt dabei ;)

2023-10-28 11:28 UTC, paul-schreiber approved these changes
Sieht gut aus :)

2023-10-28 13:34 UTC, merged